apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  selector:
    app: express
  type: NodePort
  ports:
  - protocol: TCP
    port: 5151
    targetPort: 5151
    nodePort: 3306